[package]
name = "hello_world"
version = "0.0.0"
publish = false

[dependencies]
rocket = "0.5.0"
lazy_static = "1.4.0"
num-bigint = { version = "0.4", optional = true }
num-traits = { version = "0.2", optional = true }
rand = "0.8"
rand_chacha = "0.3"
nalgebra = "0.32.3"
